name: Generate GitHub Profile Cards

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate profile cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ArfaMunam47
          BRANCH_NAME: main
          UTC_OFFSET: 5
          AUTO_PUSH: true

          # Your main visual theme
          THEME: github_dark

          # Glass-like entrance animation
          ANIMATION: rise
          DURATION: 3

          # Display name
          NAME: Arfa
