name: Generate GitHub Profile Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub profile cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ArfaMunam47
          BRANCH_NAME: main
          UTC_OFFSET: 5
          AUTO_PUSH: true
          THEME: github_dark
          ANIMATION: rise
          DURATION: 3
