name: Update Activity Trail

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate activity heatmap
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ArfaMunam47
          template: classic
          base: ""
          config_timezone: Asia/Karachi

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_isocalendar_colors: |
            color:
              - "#17151A"
              - "#3A202B"
              - "#6B3A4A"
              - "#9B506A"
              - "#D16B88"

      - name: Commit activity graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add activity.svg
          git diff --cached --quiet || git commit -m "Update activity trail"
          git push
