name: Update Activity Trail

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  activity-trail:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Activity Trail
        uses: lowlighter/metrics@latest
        with:
          filename: activity-trail.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ArfaMunam47

          template: classic

          base: ""

          config_timezone: Asia/Karachi
          config_display: large
          config_padding: 0

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          extras_js: |
            document.querySelector(".field.calendar")?.remove()

          extras_css: |

            svg {
              background: #17151A !important;
            }

            text {
              fill: #E8C8D2 !important;
            }

            rect {
              stroke: #17151A !important;
            }

            .calendar-graph rect {
              rx: 3px !important;
              ry: 3px !important;
            }

            .calendar-graph rect[data-level="0"] {
              fill: #241D22 !important;
            }

            .calendar-graph rect[data-level="1"] {
              fill: #4A2935 !important;
            }

            .calendar-graph rect[data-level="2"] {
              fill: #713B4D !important;
            }

            .calendar-graph rect[data-level="3"] {
              fill: #A34F6A !important;
            }

            .calendar-graph rect[data-level="4"] {
              fill: #D16B88 !important;
            }
