name: GitHub Profile Summary Cards

on:
  workflow_dispatch:

  schedule:
    - cron: "17 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ArfaMunam47
          BRANCH_NAME: main
          UTC_OFFSET: 5
          AUTO_PUSH: true
          THEME: github_dark
          ANIMATION: load
          DURATION: 3
